# Generated by Django 5.0.6 on 2024-06-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_qapair'),
    ]

    operations = [
        migrations.AddField(
            model_name='qapair',
            name='wiki_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
