# Generated by Django 5.0.6 on 2024-06-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_qapair_wiki_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qapair',
            name='wiki_url',
        ),
        migrations.AlterField(
            model_name='qapair',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
